HS2-CDH: ImageProcessor::ImageDecompressorTester Class Reference
ImageProcessor::ImageDecompressorTester Class Reference
Public Member Functions
ImageDecompressorTester ()
Construct the ImageDecompressor test harness.
~ImageDecompressorTester ()
Destroy the ImageDecompressor test harness.
void testEmptyInputPath ()
Verify command handling for an empty input path.
void testEmptyOutputDir ()
Verify command handling for an empty output directory path.
void testImageSampleLenTooLarge ()
Verify command handling when bitstream length exceeds allowed limits.
Static Public Attributes
static const U32 MAX_HISTORY_SIZE = 10
static const FwEnumStoreType TEST_INSTANCE_ID = 0
static const FwSizeType TEST_INSTANCE_QUEUE_DEPTH = 10
static const U32 CMD_SEQ = 0
Private Member Functions
void connectPorts ()
Connect component ports for the test harness.
void initComponents ()
Initialize components used by the test harness.
void sendDecompressCommand (const char *input_path, const char *output_dir, U64 image_sample_len)
Send a DECOMPRESS_IMAGE command with provided arguments.
void assertFailure (FwOpcodeType opcode, const Fw::CmdStringArg &input_path, I32 error_code)
Assert that the latest command response indicates failure.
Private Attributes
ImageDecompressor component
Detailed Description
Definition at line 15 of file ImageDecompressorTester.hpp.
Constructor & Destructor Documentation
ImageDecompressorTester()
ImageProcessor::ImageDecompressorTester::ImageDecompressorTester ()
Construct the ImageDecompressor test harness.
Postcondition
Test harness and test component instances are constructed.
Definition at line 18 of file ImageDecompressorTester.cpp.
References connectPorts(), and initComponents().
~ImageDecompressorTester()
ImageProcessor::ImageDecompressorTester::~ImageDecompressorTester ()
Destroy the ImageDecompressor test harness.
Postcondition
Resources owned by the test harness are released.
Definition at line 27 of file ImageDecompressorTester.cpp.
Member Function Documentation
assertFailure()
void ImageProcessor::ImageDecompressorTester::assertFailure (FwOpcodeType opcode, const Fw::CmdStringArg & input_path, I32 error_code) private
Assert that the latest command response indicates failure.
Parameters
[in] opcode Command opcode expected in the response.
[in] input_path Input path associated with the command under test.
[in] error_code Expected error code reported by the component.
Precondition
A command response has been produced by the component under test.
Postcondition
Test assertions validate expected failure metadata.
Parameters
[in] opcode Command opcode expected in the response.
[in] input_path Input path associated with the command under test.
[in] error_code Expected error code reported by the component.
Definition at line 80 of file ImageDecompressorTester.cpp.
Referenced by testEmptyInputPath(), testEmptyOutputDir(), and testImageSampleLenTooLarge().
connectPorts()
void ImageProcessor::ImageDecompressorTester::connectPorts () private
Connect component ports for the test harness.
Precondition
Test harness and component instances are constructed.
Postcondition
Required input and output ports are connected.
Referenced by ImageDecompressorTester().
initComponents()
void ImageProcessor::ImageDecompressorTester::initComponents () private
Initialize components used by the test harness.
Precondition
Port connections are complete.
Postcondition
Components are initialized and ready for test execution.
Referenced by ImageDecompressorTester().
sendDecompressCommand()
void ImageProcessor::ImageDecompressorTester::sendDecompressCommand (const char * input_path, const char * output_dir, U64 image_sample_len) private
Send a DECOMPRESS_IMAGE command with provided arguments.
Parameters
[in] input_path Path to the input bitstream file.
[in] output_dir Path to the output directory.
[in] image_sample_len Number of bytes to provide to the command.
Precondition
input_path and output_dir point to valid C strings.
Postcondition
The command is dispatched to the component under test.
Parameters
[in] input_path Path to the input bitstream file.
[in] output_dir Path to the output directory.
[in] image_sample_len Number of bytes to provide to the command.
Definition at line 64 of file ImageDecompressorTester.cpp.
Referenced by testEmptyInputPath(), testEmptyOutputDir(), and testImageSampleLenTooLarge().
testEmptyInputPath()
void ImageProcessor::ImageDecompressorTester::testEmptyInputPath ()
Verify command handling for an empty input path.
Postcondition
Expected command rejection behavior is validated.
Definition at line 34 of file ImageDecompressorTester.cpp.
References assertFailure(), and sendDecompressCommand().
testEmptyOutputDir()
void ImageProcessor::ImageDecompressorTester::testEmptyOutputDir ()
Verify command handling for an empty output directory path.
Postcondition
Expected command rejection behavior is validated.
Definition at line 43 of file ImageDecompressorTester.cpp.
References assertFailure(), and sendDecompressCommand().
testImageSampleLenTooLarge()
void ImageProcessor::ImageDecompressorTester::testImageSampleLenTooLarge ()
Verify command handling when bitstream length exceeds allowed limits.
Postcondition
Expected command rejection behavior is validated.
Definition at line 52 of file ImageDecompressorTester.cpp.
References assertFailure(), and sendDecompressCommand().
Member Data Documentation
CMD_SEQ
const U32 ImageProcessor::ImageDecompressorTester::CMD_SEQ = 0 static
Definition at line 20 of file ImageDecompressorTester.hpp.
component
ImageDecompressor ImageProcessor::ImageDecompressorTester::component private
Definition at line 89 of file ImageDecompressorTester.hpp.
MAX_HISTORY_SIZE
const U32 ImageProcessor::ImageDecompressorTester::MAX_HISTORY_SIZE = 10 static
Definition at line 17 of file ImageDecompressorTester.hpp.
TEST_INSTANCE_ID
const FwEnumStoreType ImageProcessor::ImageDecompressorTester::TEST_INSTANCE_ID = 0 static
Definition at line 18 of file ImageDecompressorTester.hpp.
TEST_INSTANCE_QUEUE_DEPTH
const FwSizeType ImageProcessor::ImageDecompressorTester::TEST_INSTANCE_QUEUE_DEPTH = 10 static
Definition at line 19 of file ImageDecompressorTester.hpp.
The documentation for this class was generated from the following files:
FlightComputer/Components/ImageProcessor/ImageDecompressor/test/ut/ImageDecompressorTester.hpp
FlightComputer/Components/ImageProcessor/ImageDecompressor/test/ut/ImageDecompressorTester.cpp