HS2-CDH: FlightComputer::EventSchedulerTester Class Reference
FlightComputer::EventSchedulerTester Class Reference final
Public Member Functions
EventSchedulerTester ()
Construction and destruction.
~EventSchedulerTester ()
Destroy the EventScheduler test harness.
void toDo ()
Tests.
Static Public Attributes
static const FwSizeType MAX_HISTORY_SIZE = 10
Constants.
static const FwEnumStoreType TEST_INSTANCE_ID = 0
Instance ID supplied to the component instance under test.
static const FwSizeType TEST_INSTANCE_QUEUE_DEPTH = 10
Queue depth supplied to the component instance under test.
Private Member Functions
void connectPorts ()
Helper functions.
void initComponents ()
Initialize components used by the test harness.
Private Attributes
EventScheduler component
Member variables.
Detailed Description
Definition at line 15 of file EventSchedulerTester.hpp.
Constructor & Destructor Documentation
EventSchedulerTester()
FlightComputer::EventSchedulerTester::EventSchedulerTester ()
Construction and destruction.
Construct the EventScheduler test harness.
Postcondition
Test harness and test component instances are constructed.
Construct the EventScheduler test harness.
Definition at line 18 of file EventSchedulerTester.cpp.
References connectPorts(), and initComponents().
~EventSchedulerTester()
FlightComputer::EventSchedulerTester::~EventSchedulerTester ()
Destroy the EventScheduler test harness.
Postcondition
Resources owned by the test harness are released.
Definition at line 28 of file EventSchedulerTester.cpp.
Member Function Documentation
connectPorts()
void FlightComputer::EventSchedulerTester::connectPorts () private
Helper functions.
Connect component ports for the test harness.
Precondition
Test harness and component instances are constructed.
Postcondition
Required input and output ports are connected.
Referenced by EventSchedulerTester().
initComponents()
void FlightComputer::EventSchedulerTester::initComponents () private
Initialize components used by the test harness.
Precondition
Port connections are complete.
Postcondition
Components are initialized and ready for test execution.
Referenced by EventSchedulerTester().
toDo()
void FlightComputer::EventSchedulerTester::toDo ()
Tests.
Placeholder test entry point.
Postcondition
Placeholder test flow is executed.
Placeholder test entry point.
Definition at line 39 of file EventSchedulerTester.cpp.
Member Data Documentation
component
EventScheduler FlightComputer::EventSchedulerTester::component private
Member variables.
The component under test.
Definition at line 91 of file EventSchedulerTester.hpp.
MAX_HISTORY_SIZE
const FwSizeType FlightComputer::EventSchedulerTester::MAX_HISTORY_SIZE = 10 static
Constants.
Maximum size of histories storing events, telemetry, and port outputs.
Definition at line 24 of file EventSchedulerTester.hpp.
TEST_INSTANCE_ID
const FwEnumStoreType FlightComputer::EventSchedulerTester::TEST_INSTANCE_ID = 0 static
Instance ID supplied to the component instance under test.
Definition at line 29 of file EventSchedulerTester.hpp.
TEST_INSTANCE_QUEUE_DEPTH
const FwSizeType FlightComputer::EventSchedulerTester::TEST_INSTANCE_QUEUE_DEPTH = 10 static
Queue depth supplied to the component instance under test.
Definition at line 34 of file EventSchedulerTester.hpp.
The documentation for this class was generated from the following files:
FlightComputer/Components/EventScheduler/test/ut/EventSchedulerTester.hpp
FlightComputer/Components/EventScheduler/test/ut/EventSchedulerTester.cpp