HS2-CDH: ImageProcessor::ImageCompressorTester Class Reference
ImageProcessor::ImageCompressorTester Class Reference
Public Member Functions
ImageCompressorTester ()
Construct the ImageCompressor test harness.
~ImageCompressorTester ()
Destroy the ImageCompressor test harness.
void testEmptyInputPath ()
Verify command handling for an empty input path.
void testEmptyOutputDir ()
Verify command handling for an empty output directory path.
void testInvalidAel ()
Verify command handling for an invalid AEL value.
void testSampleLenTooLarge ()
Verify command handling when sample length exceeds allowed limits.
Static Public Attributes
static const U32 MAX_HISTORY_SIZE = 10
static const FwEnumStoreType TEST_INSTANCE_ID = 0
static const FwSizeType TEST_INSTANCE_QUEUE_DEPTH = 10
static const U32 CMD_SEQ = 0
Private Member Functions
void connectPorts ()
Connect component ports for the test harness.
void initComponents ()
Initialize components used by the test harness.
void sendCompressCommand (const char *input_path, const char *output_dir, I32 ael, U64 sample_len)
Send a COMPRESS_IMAGE command with provided arguments.
void assertFailure (FwOpcodeType opcode, const Fw::CmdStringArg &input_path, I32 error_code)
Assert that the latest command response indicates failure.
Private Attributes
ImageCompressor component
Detailed Description
Definition at line 15 of file ImageCompressorTester.hpp.
Constructor & Destructor Documentation
ImageCompressorTester()
ImageProcessor::ImageCompressorTester::ImageCompressorTester ()
Construct the ImageCompressor test harness.
Postcondition
Test harness and test component instances are constructed.
Definition at line 18 of file ImageCompressorTester.cpp.
References connectPorts(), and initComponents().
~ImageCompressorTester()
ImageProcessor::ImageCompressorTester::~ImageCompressorTester ()
Destroy the ImageCompressor test harness.
Postcondition
Resources owned by the test harness are released.
Definition at line 27 of file ImageCompressorTester.cpp.
Member Function Documentation
assertFailure()
void ImageProcessor::ImageCompressorTester::assertFailure (FwOpcodeType opcode, const Fw::CmdStringArg & input_path, I32 error_code) private
Assert that the latest command response indicates failure.
Parameters
[in] opcode Command opcode expected in the response.
[in] input_path Input path associated with the command under test.
[in] error_code Expected error code reported by the component.
Precondition
A command response has been produced by the component under test.
Postcondition
Test assertions validate expected failure metadata.
Parameters
[in] opcode Command opcode expected in the response.
[in] input_path Input path associated with the command under test.
[in] error_code Expected error code reported by the component.
Definition at line 92 of file ImageCompressorTester.cpp.
connectPorts()
void ImageProcessor::ImageCompressorTester::connectPorts () private
Connect component ports for the test harness.
Precondition
Test harness and component instances are constructed.
Postcondition
Required input and output ports are connected.
Referenced by ImageCompressorTester().
initComponents()
void ImageProcessor::ImageCompressorTester::initComponents () private
Initialize components used by the test harness.
Precondition
Port connections are complete.
Postcondition
Components are initialized and ready for test execution.
Referenced by ImageCompressorTester().
sendCompressCommand()
void ImageProcessor::ImageCompressorTester::sendCompressCommand (const char * input_path, const char * output_dir, I32 ael, U64 sample_len) private
Send a COMPRESS_IMAGE command with provided arguments.
Parameters
[in] input_path Path to the input image file.
[in] output_dir Path to the output directory.
[in] ael Absolute error limit for compression.
[in] sample_len Number of samples to provide to the command.
Precondition
input_path and output_dir point to valid C strings.
Postcondition
The command is dispatched to the component under test.
Parameters
[in] input_path Path to the input image file.
[in] output_dir Path to the output directory.
[in] ael Absolute error limit for compression.
[in] sample_len Number of samples to provide to the command.
Definition at line 74 of file ImageCompressorTester.cpp.
testEmptyInputPath()
void ImageProcessor::ImageCompressorTester::testEmptyInputPath ()
Verify command handling for an empty input path.
Postcondition
Expected command rejection behavior is validated.
Definition at line 34 of file ImageCompressorTester.cpp.
testEmptyOutputDir()
void ImageProcessor::ImageCompressorTester::testEmptyOutputDir ()
Verify command handling for an empty output directory path.
Postcondition
Expected command rejection behavior is validated.
Definition at line 43 of file ImageCompressorTester.cpp.
testInvalidAel()
void ImageProcessor::ImageCompressorTester::testInvalidAel ()
Verify command handling for an invalid AEL value.
Postcondition
Expected command rejection behavior is validated.
Definition at line 52 of file ImageCompressorTester.cpp.
testSampleLenTooLarge()
void ImageProcessor::ImageCompressorTester::testSampleLenTooLarge ()
Verify command handling when sample length exceeds allowed limits.
Postcondition
Expected command rejection behavior is validated.
Definition at line 61 of file ImageCompressorTester.cpp.
Member Data Documentation
CMD_SEQ
const U32 ImageProcessor::ImageCompressorTester::CMD_SEQ = 0 static
Definition at line 20 of file ImageCompressorTester.hpp.
component
ImageCompressor ImageProcessor::ImageCompressorTester::component private
Definition at line 96 of file ImageCompressorTester.hpp.
MAX_HISTORY_SIZE
const U32 ImageProcessor::ImageCompressorTester::MAX_HISTORY_SIZE = 10 static
Definition at line 17 of file ImageCompressorTester.hpp.
TEST_INSTANCE_ID
const FwEnumStoreType ImageProcessor::ImageCompressorTester::TEST_INSTANCE_ID = 0 static
Definition at line 18 of file ImageCompressorTester.hpp.
TEST_INSTANCE_QUEUE_DEPTH
const FwSizeType ImageProcessor::ImageCompressorTester::TEST_INSTANCE_QUEUE_DEPTH = 10 static
Definition at line 19 of file ImageCompressorTester.hpp.
The documentation for this class was generated from the following files:
FlightComputer/Components/ImageProcessor/ImageCompressor/test/ut/ImageCompressorTester.hpp
FlightComputer/Components/ImageProcessor/ImageCompressor/test/ut/ImageCompressorTester.cpp